In [1]:
# write your code here!
import numpy as np
def create_board():
    return np.zeros((3,3), dtype=int)
board = create_board()

In [2]:
board

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
# write your code here!
def place(board:np.array, player:int, position:tuple):
    x0, x1 = position
    if board[x0,x1] == 0:
        board[x0,x1] = player         

In [4]:
place(board, 1, (0,0))

In [5]:
# write your code here!
def possibilities(board):
    return list(zip(*np.where(board == 0)))

possibilities(board)

[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

In [6]:
import random 
random.seed(1)

# write your code here!
def random_place(board, player):
    choice = random.choice(possibilities(board))
    place(board, player, choice)

random_place(board, 2)
    
board

array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

In [7]:
def random_place(board, player):
    selections = possibilities(board)
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
    return board

In [8]:
random.seed(1)
board = create_board()

# write your code here!
for i in range(3):
    for player in [1, 2]:
        random_place(board, player)
print(board)
print(possibilities(board))

[[2 2 1]
 [0 1 0]
 [0 1 2]]
[(1, 0), (1, 2), (2, 0)]


In [9]:
X = np.ones((3,3))
X[0,2] = 0
X[1,1] = 0
X[2,1] = 0
X

array([[1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [10]:
def row_win(board, player):
    if np.any(np.all(board==player, axis=1)):
        return True
    else:
        return False

row_win(board, 1)

False

In [11]:
def col_win(board, player):
    if np.any(np.all(board==player, axis=0)): # this checks if any column contains all positions equal to player
        return True
    else:
        return False

col_win(board, 1)
False

False

In [12]:
def diag_win(board, player):
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        return True
    else:
        return False

diag_win(board, 2)
True

True

In [13]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    print(winner)
    return winner

evaluate(board)

0


0

### Exercise 10

In this exercise, we will use all the functions we have made to simulate an entire game.

#### Instructions 

- `create_board()`, `random_place(board, player)`, and `evaluate(board)` have been created in previous exercises. Create a function `play_game()` that:
    - Creates a board.
    - Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.
    - Evaluates the board for a winner after each placement.
    - Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).
- Call play_game 1000 times, and store the results of the game in a list called `results`.

In [14]:
def create_board():
    return np.zeros((3,3), dtype=int)

In [15]:
def random_place(board, player):
    selections = possibilities(board)
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
    return board

In [29]:
def row_win(board, player):
    if np.any(np.all(board==player, axis=1)):
        return True
    else:
        return False
    
def col_win(board, player):
    if np.any(np.all(board==player, axis=0)): # this checks if any column contains all positions equal to player
        return True
    else:
        return False
    
def diag_win(board, player):
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        return True
    else:
        return False
    
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            return player
    if np.all(board != 0) and winner == 0:
        return 3

In [45]:
def create_board():
    return np.zeros((3,3), dtype=int)

In [46]:
def random_place(board, player):
    selections = possibilities(board)
    if len(selections) > 0:
        selection = random.choice(selections)
        place(board, player, selection)
    return board

In [47]:
def row_win(board, player):
    if np.any(np.all(board==player,axis=1)): # this checks if any row contains all positions equal to player.
        return True
    else:
        return False

In [48]:
def col_win(board, player):
    if np.any(np.all(board==player,axis=0)):
        return True
    else:
        return False

In [49]:
def diag_win(board, player):
    if np.all(np.diag(board)==player) or np.all(np.diag(np.fliplr(board))==player):
        # np.diag returns the diagonal of the array
        # np.fliplr rearranges columns in reverse order
        return True
    else:
        return False

In [50]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            winner = player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

In [58]:
random.seed(1)

# write your code here!
def play_game():
    board = create_board()
    winner = 0
    while winner == 0:
        for player in [1, 2]:
            if np.all(board == 0):
                board[1,1] = 1
            else:
                random_place(board, player)
                winner = evaluate(board)
                if winner != 0:
                    break
    return winner

lst_winners = []
for i in range(1000):
    lst_winners.append(play_game())
    
print(lst_winners.count(1))

716


#### Exercise 11

In the previous exercise, we see that when guessing at random, it's better to go first, as expected. Let's see if Player 1 can improve their strategy. 

#### Instructions 
- Create a function `play_strategic_game()`, where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.
- Call `play_strategic_game` 1000 times.

In [ ]:
random.seed(1)

# write your code here
